<?php
// This file generated by Propel 1.6.9-dev convert-conf target
return array (
  'BasePortfolioArticle' => 'site_name/om/BasePortfolioArticle.php',
  'BasePortfolioArticlePeer' => 'site_name/om/BasePortfolioArticlePeer.php',
  'BasePortfolioArticleQuery' => 'site_name/om/BasePortfolioArticleQuery.php',
  'BasePortfolioCategorie' => 'site_name/om/BasePortfolioCategorie.php',
  'BasePortfolioCategoriePeer' => 'site_name/om/BasePortfolioCategoriePeer.php',
  'BasePortfolioCategorieQuery' => 'site_name/om/BasePortfolioCategorieQuery.php',
  'PortfolioArticle' => 'site_name/PortfolioArticle.php',
  'PortfolioArticlePeer' => 'site_name/PortfolioArticlePeer.php',
  'PortfolioArticleQuery' => 'site_name/PortfolioArticleQuery.php',
  'PortfolioArticleTableMap' => 'site_name/map/PortfolioArticleTableMap.php',
  'PortfolioCategorie' => 'site_name/PortfolioCategorie.php',
  'PortfolioCategoriePeer' => 'site_name/PortfolioCategoriePeer.php',
  'PortfolioCategorieQuery' => 'site_name/PortfolioCategorieQuery.php',
  'PortfolioCategorieTableMap' => 'site_name/map/PortfolioCategorieTableMap.php',
);