<?php
// This file generated by Propel 1.6.9-dev convert-conf target
return array (
  'BasePortfolioArticle' => 'portfolio/om/BasePortfolioArticle.php',
  'BasePortfolioArticlePeer' => 'portfolio/om/BasePortfolioArticlePeer.php',
  'BasePortfolioArticleQuery' => 'portfolio/om/BasePortfolioArticleQuery.php',
  'BasePortfolioCategorie' => 'portfolio/om/BasePortfolioCategorie.php',
  'BasePortfolioCategoriePeer' => 'portfolio/om/BasePortfolioCategoriePeer.php',
  'BasePortfolioCategorieQuery' => 'portfolio/om/BasePortfolioCategorieQuery.php',
  'PortfolioArticle' => 'portfolio/PortfolioArticle.php',
  'PortfolioArticlePeer' => 'portfolio/PortfolioArticlePeer.php',
  'PortfolioArticleQuery' => 'portfolio/PortfolioArticleQuery.php',
  'PortfolioArticleTableMap' => 'portfolio/map/PortfolioArticleTableMap.php',
  'PortfolioCategorie' => 'portfolio/PortfolioCategorie.php',
  'PortfolioCategoriePeer' => 'portfolio/PortfolioCategoriePeer.php',
  'PortfolioCategorieQuery' => 'portfolio/PortfolioCategorieQuery.php',
  'PortfolioCategorieTableMap' => 'portfolio/map/PortfolioCategorieTableMap.php',
);